spring:
  application:
    name: stu-info-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stu_info2026?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations: classpath:schema.sql,classpath:schema-routines.sql,classpath:schema-post-data.sql

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cd.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081

jwt:
  secret: stu-info-2026-security-jwt-secret-key-for-spring-security
  expiration-minutes: 720
